version: "3"

# Run `docker-compose up dev` for bootstrapping your development environment
# Doing so will expose NBXplorer, Bitcoind RPC and postgres port to the host so that tests can Run,
# The Visual Studio launch setting `Docker-regtest` is configured to use this environment.
services:
  default:
    image: alpine:3.7
    depends_on:
      - postgres
      - server
      - walletd

  server:
    image: ${ARRR_SERVER_IMAGE:-kardingson/pirate_btcpay_server}:${ARRR_SERVER_TAG:-latest}
    command: "dotnet BTCPayServer.dll"
    environment:
      "BTCPAY_BIND": 0.0.0.0:14142
      "BTCPAY_HttpsUseDefaultCertificate": "false"
      "BTCPAY_VERBOSE": "true"
      "BTCPAY_BUNDLEJSCSS": "false"
      "BTCPAY_ALLOW-ADMIN-REGISTRATION": "true"
      "BTCPAY_DISABLE-REGISTRATION": "false"
      "ASPNETCORE_ENVIRONMENT": "Development"
      "BTCPAY_CHAINS": "arrr"
      "BTCPAY_POSTGRES": "User ID=postgres;Include Error Detail=true;Host=postgres;Port=5432;Database=btcpayserver"
      "BTCPAY_ARRR_DAEMON_URI": "http://walletd:8000"
      "BTCPAY_ARRR_WALLET_DAEMON_URI": "http://walletd:8000"
      "BTCPAY_ARRR_WALLET_DAEMON_WALLETDIR": "/"
    ports:
      - 14142:14142

  walletd:
    image: ${ARRR_WALLETD_IMAGE:-kardingson/pirate_btcpay_walletd}:${ARRR_WALLETD_TAG:-v0.1.1}
    command: "./walletd"
    environment:
      RUST_LOG: info
      BTCPAYSERVER_starting_height: 3602130
      BTCPAYSERVER_fvk: zxviews1qdchfgzdqyqqpqqjg4l47nd9t5m0j6kzwsxaf84ktc74uhc4nnnu8fgwyjk0958xnytz45xhudjar87c97q5jqq52duq9s3vqhntt0udhxczqfzm25aqsnuhk84pmpt9mahah4eqtjjjqqywwlxg82e6t9ngm9glr9qhxcdttc2mkkcwjr9clqsskx7u2fwlh0prseppxw8ap7fm5s9zxatf6a4lt8tf9j9kkywhpqfqpr5avtcrc8ahndzssjjppsnqupcxecypplsfjgwek
      BTCPAYSERVER_lwd_url: https://lightd1.pirate.black:443
      BTCPAYSERVER_poll_interval: "10"
      BTCPAYSERVER_notify_host: http://server:14142
      BTCPAYSERVER_confirmations: "6"
    expose:
      - 8000
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS -X POST http://localhost:8000/get_height >/dev/null || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s

  postgres:
    image:  postgres:13.4
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "39372:5432"
    expose:
      - "5432"

